[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "web: gunicorn myproject.wsgi:application --bind=0.0.0.0:$PORT --workers=2 --threads=4 --worker-class=gevent --timeout=0"
healthcheckPath = "/"
restartPolicyType = "on_failure"
